version: '3'

services:
  backend_server:
    build:
        context: ./backend
        dockerfile: Docker-messaging-system
    image: messaging-system
    ports:
      - "8000:8000"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./populate.js:/docker-entrypoint-initdb.d/populate.js
